on:
  push:
    branches:
      - master
  pull_request:

name: Continuous integration

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Start bitcoin node
        run: docker compose up -d
      - name: Wait for container to run
        run: ./scripts/wait_for_container.sh bitcoin
      - name: Wait for electrs to be ready
        run: ./scripts/wait_for_electrs.sh
      - name: Test
        run: cargo test
      - name: Stop bitcoin node
        run: ./scripts/stop_node.sh