on:
  push:
    branches:
      - master
  pull_request:

name: Continuous integration

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test
